import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { EnvSchema, SchemaDescriptor } from '../core/types.js';

export function runGenExample(flags: Record<string, string>): void {
  const schemaPath = resolve(flags['schema'] ?? 'env-schema.json');
  const outputPath = resolve(flags['output'] ?? '.env.example');

  if (!existsSync(schemaPath)) {
    process.stderr.write(`❌ Schema file not found: ${schemaPath}\n`);
    process.stderr.write(`   Run: npx env-safe-guard init\n`);
    process.exit(1);
  }

  const schema = JSON.parse(readFileSync(schemaPath, 'utf8')) as EnvSchema;

  const lines: string[] = [
    '# Generated by env-safe-guard',
    '# Fill in real values and rename to .env (never commit .env)',
    '',
  ];

  for (const [key, entry] of Object.entries(schema)) {
    const isDescriptor = typeof entry !== 'string';
    const descriptor = isDescriptor ? (entry as SchemaDescriptor) : null;
    const typeStr = isDescriptor ? descriptor!.type : (entry as string);
    const isOptional = typeStr.endsWith('?');
    const hasDefault = descriptor?.default !== undefined;
    const isSecret = descriptor?.secret === true;

    const parts: string[] = [];
    parts.push(isOptional ? 'optional' : 'required');
    if (hasDefault) parts.push(`default: ${String(descriptor!.default)}`);
    if (isSecret) parts.push('SECRET — never log or share');

    lines.push(`# ${parts.join(', ')}`);
    lines.push(`${key}=`);
    lines.push('');
  }

  writeFileSync(outputPath, lines.join('\n'));
  process.stdout.write(`✅ Created ${outputPath}\n`);
  process.stdout.write(`   Fill in values and rename to .env\n`);
  process.stdout.write(`   ⚠️  Never commit .env — only commit .env.example\n`);
}
